package dto;
// Generated 12-jun-2019 23:25:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int idAlumno;
     private String nombreAlumno;
     private Date fechaNacAlumno;
     private Set notas = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Alumno(int idAlumno, String nombreAlumno, Date fechaNacAlumno, Set notas) {
       this.idAlumno = idAlumno;
       this.nombreAlumno = nombreAlumno;
       this.fechaNacAlumno = fechaNacAlumno;
       this.notas = notas;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getNombreAlumno() {
        return this.nombreAlumno;
    }
    
    public void setNombreAlumno(String nombreAlumno) {
        this.nombreAlumno = nombreAlumno;
    }
    public Date getFechaNacAlumno() {
        return this.fechaNacAlumno;
    }
    
    public void setFechaNacAlumno(Date fechaNacAlumno) {
        this.fechaNacAlumno = fechaNacAlumno;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


