package dto;
// Generated 12-jun-2019 23:25:35 by Hibernate Tools 4.3.1



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private int idNota;
     private Alumno alumno;
     private Asignatura asignatura;
     private Short nota;

    public Nota() {
    }

	
    public Nota(int idNota) {
        this.idNota = idNota;
    }
    public Nota(int idNota, Alumno alumno, Asignatura asignatura, Short nota) {
       this.idNota = idNota;
       this.alumno = alumno;
       this.asignatura = asignatura;
       this.nota = nota;
    }
   
    public int getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(int idNota) {
        this.idNota = idNota;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public Short getNota() {
        return this.nota;
    }
    
    public void setNota(Short nota) {
        this.nota = nota;
    }




}


